import { PrismaClient, PlaceType } from "@prisma/client";

const prisma = new PrismaClient();

const places = [
  {
    id: 1,
    name: "Гора Белуха",
    category: "Природа",
    description: "Высочайшая вершина Горного Алтая (4509 м). Священная гора, объект всемирного наследия ЮНЕСКО.",
    price: "25000 ₽",
    rating: 4.9,
    tags: ["Гора", "Природа", "История"],
    image: "https://images.unsplash.com/photo-1655047682631-5c4d3330d9b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 49.8078,
    lng: 86.5944,
    type: "attraction" as PlaceType,
  },
  {
    id: 2,
    name: "Телецкое озеро",
    category: "Озера",
    description: "Одно из глубочайших озёр России, называемое «Золотым». Чистейшая вода и живописные берега.",
    price: "8000 ₽",
    rating: 4.8,
    tags: ["Озеро", "Природа", "Экскурсии"],
    image: "https://images.unsplash.com/photo-1758920206594-b20e4ab58a8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.5172,
    lng: 87.7142,
    type: "attraction" as PlaceType,
  },
  {
    id: 3,
    name: "Мультинские озера",
    category: "Озера",
    description: "Каскад из пяти живописных озёр с бирюзовой водой в окружении хвойных лесов и горных вершин.",
    price: "12000 ₽",
    rating: 4.9,
    tags: ["Озера", "Природа", "Активности"],
    image: "https://images.unsplash.com/photo-1654665467374-f17380de7937?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.0580,
    lng: 85.8083,
    type: "attraction" as PlaceType,
  },
  {
    id: 4,
    name: "Чуйский тракт",
    category: "Экскурсии",
    description: "Одна из красивейших дорог мира. Проходит через все природные зоны Алтая протяжённостью 968 км.",
    price: "15000 ₽",
    rating: 4.7,
    tags: ["Дорога", "Экскурсии", "История"],
    image: "https://images.unsplash.com/photo-1716479852367-336a095cb2cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.3500,
    lng: 87.3500,
    type: "attraction" as PlaceType,
  },
  {
    id: 5,
    name: "Каракольские озера",
    category: "Озера",
    description: "Семь горных озёр ледникового происхождения на высоте 1800–2100 м. Альпийские луга и редкие растения.",
    price: "10000 ₽",
    rating: 4.8,
    tags: ["Озера", "Природа", "Горы"],
    image: "https://images.unsplash.com/photo-1747138167921-223e530279cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.0333,
    lng: 85.9667,
    type: "attraction" as PlaceType,
  },
  {
    id: 6,
    name: "Ледники Актру",
    category: "Горы",
    description: "Уникальный ледниковый комплекс в Северо-Чуйском хребте. Идеальное место для альпинизма и треккинга.",
    price: "18000 ₽",
    rating: 4.9,
    tags: ["Ледник", "Горы", "Активности"],
    image: "https://images.unsplash.com/photo-1566519804250-b33d0f66d88b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.0750,
    lng: 87.6500,
    type: "attraction" as PlaceType,
  },
  {
    id: 7,
    name: "Камышлинский водопад",
    category: "Водопады",
    description: "Живописный двухкаскадный водопад высотой 12 метров на левом берегу реки Катунь.",
    price: "3000 ₽",
    rating: 4.6,
    tags: ["Водопад", "Природа"],
    image: "https://images.unsplash.com/photo-1551060880-be14732be9f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.6583,
    lng: 85.9167,
    type: "attraction" as PlaceType,
  },
  {
    id: 8,
    name: "Долина Чулышман",
    category: "Природа",
    description: "Живописная речная долина с каньонами, водопадами и древними петроглифами. Труднодоступное место.",
    price: "14000 ₽",
    rating: 4.8,
    tags: ["Долина", "Природа", "История"],
    image: "https://images.unsplash.com/photo-1602677690568-a3d44545973f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.3167,
    lng: 88.1000,
    type: "attraction" as PlaceType,
  },
  {
    id: 9,
    name: "Патмосский монастырь",
    category: "Культура",
    description: "Женский монастырь на острове Патмос на реке Катунь. Уникальное место силы и духовности.",
    price: "4000 ₽",
    rating: 4.7,
    tags: ["Культура", "История", "Экскурсии"],
    image: "https://images.unsplash.com/photo-1650535877096-928df2bb6365?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.4033,
    lng: 86.0014,
    type: "attraction" as PlaceType,
  },
  {
    id: 10,
    name: "Перевал Кату-Ярык",
    category: "Активности",
    description: "Экстремальный горный серпантин с уклоном до 70%. Захватывающие виды на долину реки Чулышман.",
    price: "9000 ₽",
    rating: 4.9,
    tags: ["Горы", "Активности", "Экскурсии"],
    image: "https://images.unsplash.com/photo-1759312507653-4bf0b5a86611?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.2500,
    lng: 87.9500,
    type: "attraction" as PlaceType,
  },
  {
    id: 11,
    name: "Семинский перевал",
    category: "Горы",
    description: "Высочайший перевал Чуйского тракта (1717 м). На вершине — кедровый лес и обелиск в честь 200-летия добровольного вхождения Алтая в состав России.",
    price: "5000 ₽",
    rating: 4.6,
    tags: ["Горы", "История", "Природа"],
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.0500,
    lng: 85.5833,
    type: "attraction" as PlaceType,
  },
  {
    id: 12,
    name: "Перевал Чике-Таман",
    category: "Горы",
    description: "Живописный серпантин с уклоном 11% и смотровыми площадками. Один из красивейших участков Чуйского тракта с панорамой горных хребтов.",
    price: "6000 ₽",
    rating: 4.7,
    tags: ["Горы", "Природа", "Экскурсии"],
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.9200,
    lng: 86.0170,
    type: "attraction" as PlaceType,
  },
  {
    id: 13,
    name: "Денисова пещера",
    category: "Культура",
    description: "Всемирно известная пещера, где были найдены останки денисовского человека — отдельного вида гоминидов возрастом 40 000 лет. Объект мирового значения.",
    price: "3000 ₽",
    rating: 4.7,
    tags: ["История", "Культура", "Наука"],
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.3972,
    lng: 84.6778,
    type: "attraction" as PlaceType,
  },
  {
    id: 14,
    name: "Гейзерное озеро",
    category: "Озера",
    description: "Уникальное термальное озеро с ярко-голубыми концентрическими кругами на дне. Питается подземными источниками и никогда не замерзает.",
    price: "7000 ₽",
    rating: 4.8,
    tags: ["Озеро", "Природа", "Уникальное"],
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.6833,
    lng: 87.7167,
    type: "attraction" as PlaceType,
  },
  {
    id: 15,
    name: "Слияние Чуи и Катуни",
    category: "Природа",
    description: "Живописное место встречи двух великих рек Алтая. Белоснежная Катунь и мутная бирюзовая Чуя образуют разительный контраст цветов.",
    price: "4000 ₽",
    rating: 4.7,
    tags: ["Природа", "Экскурсии", "Пейзаж"],
    image: "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.4900,
    lng: 86.5850,
    type: "attraction" as PlaceType,
  },
  {
    id: 16,
    name: "Долина Марса",
    category: "Природа",
    description: "Фантастическая разноцветная долина Кызыл-Чин с красными, оранжевыми и фиолетовыми слоями горных пород. Настоящий «алтайский Марс».",
    price: "11000 ₽",
    rating: 4.9,
    tags: ["Природа", "Уникальное", "Горы"],
    image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 49.9833,
    lng: 88.0500,
    type: "attraction" as PlaceType,
  },
  {
    id: 17,
    name: "Каменные грибы Аккурум",
    category: "Природа",
    description: "Причудливые каменные столбы с широкими «шляпками» на берегу Чулышмана. Результат тысячелетней эрозии — одно из самых необычных природных образований Алтая.",
    price: "13000 ₽",
    rating: 4.8,
    tags: ["Природа", "Уникальное", "Активности"],
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.1833,
    lng: 87.9000,
    type: "attraction" as PlaceType,
  },
  {
    id: 18,
    name: "Озеро Ая",
    category: "Озера",
    description: "Тёплое карстовое озеро с изумрудной водой у слияния Катуни и Аи. Одно из немногих мест Алтая, где можно купаться — летом вода прогревается до 22°C.",
    price: "3500 ₽",
    rating: 4.5,
    tags: ["Озеро", "Купание", "Природа"],
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.9170,
    lng: 85.8170,
    type: "attraction" as PlaceType,
  },
  {
    id: 19,
    name: "Петроглифы Калбак-Таш",
    category: "Культура",
    description: "Крупнейшее скопление наскальных рисунков Горного Алтая. Более 5000 петроглифов от эпохи бронзы до средневековья на скале над Чуйским трактом.",
    price: "4500 ₽",
    rating: 4.6,
    tags: ["История", "Культура", "Экскурсии"],
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.4170,
    lng: 86.5000,
    type: "attraction" as PlaceType,
  },
  {
    id: 20,
    name: "Курайская степь",
    category: "Природа",
    description: "Высокогорная степь на высоте 1500 м с бескрайним видом на Северо-Чуйский хребет. Место невероятных рассветов и сурового горного простора.",
    price: "8000 ₽",
    rating: 4.7,
    tags: ["Природа", "Пейзаж", "Горы"],
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.2333,
    lng: 87.7833,
    type: "attraction" as PlaceType,
  },
  {
    id: 21,
    name: "Водопад Корбу",
    category: "Водопады",
    description: "Мощный водопад высотой 12 метров, впадающий в Телецкое озеро. Добраться можно только по воде — на катере от посёлка Артыбаш.",
    price: "6000 ₽",
    rating: 4.7,
    tags: ["Водопад", "Природа", "Экскурсии"],
    image: "https://images.unsplash.com/photo-1565438370856-cae3b0a5be43?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.5833,
    lng: 87.7833,
    type: "attraction" as PlaceType,
  },
  {
    id: 22,
    name: "Чемальская ГЭС",
    category: "Экскурсии",
    description: "Старейшая ГЭС Сибири 1935 года постройки на реке Катунь. Рядом — подвесной мост, остров Патмос и живописный каньон.",
    price: "2500 ₽",
    rating: 4.4,
    tags: ["История", "Экскурсии", "Культура"],
    image: "https://images.unsplash.com/photo-1504700610630-ac6aba3536d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.4020,
    lng: 85.9830,
    type: "attraction" as PlaceType,
  },
  {
    id: 23,
    name: "Уймонская долина",
    category: "Природа",
    description: "Широкая межгорная котловина у подножия Катунского хребта. Здесь живут потомки старообрядцев, а на горизонте сияет белоснежная Белуха.",
    price: "9000 ₽",
    rating: 4.7,
    tags: ["Природа", "История", "Горы"],
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.1833,
    lng: 85.9670,
    type: "attraction" as PlaceType,
  },
  {
    id: 24,
    name: "Озеро Манжерок",
    category: "Озера",
    description: "Живописное озеро у подножия горы Малая Синюха. Рядом — курорт Манжерок с канатной дорогой и смотровой площадкой над долиной Катуни.",
    price: "4000 ₽",
    rating: 4.5,
    tags: ["Озеро", "Курорт", "Активности"],
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.8500,
    lng: 85.8667,
    type: "attraction" as PlaceType,
  },
  {
    id: 25,
    name: "Перевал Кара-Тюрек",
    category: "Горы",
    description: "Высокогорный перевал (3060 м) с лучшей панорамой на Белуху и все ледники Катунского хребта. Любимый маршрут трекеров и фотографов.",
    price: "20000 ₽",
    rating: 4.9,
    tags: ["Горы", "Треккинг", "Природа"],
    image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 49.9670,
    lng: 86.6330,
    type: "attraction" as PlaceType,
  },
  // Отели
  {
    id: 101,
    name: "Алтай Resort & SPA",
    category: "4 звезды",
    description: "Крупнейший курорт Горного Алтая на берегу озера Манжерок. Собственная горнолыжная трасса, канатная дорога, термальный SPA-комплекс и панорамные рестораны.",
    price: "от 8 500 ₽/ночь",
    rating: 4.7,
    tags: ["SPA", "Горнолыжный", "Ресторан"],
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.8520,
    lng: 85.8680,
    type: "hotel" as PlaceType,
  },
  {
    id: 102,
    name: "Турбаза «Артыбаш»",
    category: "3 звезды",
    description: "Уютная база отдыха на берегу Телецкого озера в посёлке Артыбаш. Отправная точка для экскурсий на катере к водопаду Корбу и по живописным берегам озера.",
    price: "от 3 200 ₽/ночь",
    rating: 4.4,
    tags: ["Озеро", "Катер", "Рыбалка"],
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.7972,
    lng: 87.2778,
    type: "hotel" as PlaceType,
  },
  {
    id: 103,
    name: "Глэмпинг «Катунь»",
    category: "Глэмпинг",
    description: "Стильные сферические домики и шатры прямо над берегом Катуни. Полное погружение в природу с комфортом: дровяная баня, завтрак с видом на горы, тишина.",
    price: "от 5 500 ₽/ночь",
    rating: 4.8,
    tags: ["Природа", "Романтика", "Баня"],
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.6200,
    lng: 85.9500,
    type: "hotel" as PlaceType,
  },
  {
    id: 104,
    name: "Горный приют «Белуха»",
    category: "Альплагерь",
    description: "Базовый лагерь для восхождений и трекинга в районе Белухи. Тёплые домики, горячее питание и опытные гиды-проводники для маршрутов любой сложности.",
    price: "от 2 800 ₽/ночь",
    rating: 4.6,
    tags: ["Треккинг", "Горы", "Гиды"],
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 49.8900,
    lng: 86.5800,
    type: "hotel" as PlaceType,
  },
  {
    id: 105,
    name: "Отель «Чемал»",
    category: "3 звезды",
    description: "Небольшой уютный отель в центре Чемала на берегу Катуни. Удобная база для экскурсий к ГЭС, острову Патмос и Камышлинскому водопаду.",
    price: "от 4 000 ₽/ночь",
    rating: 4.3,
    tags: ["Центр", "Экскурсии", "Завтрак"],
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.4050,
    lng: 86.0100,
    type: "hotel" as PlaceType,
  },
  {
    id: 106,
    name: "Эко-усадьба «Уймон»",
    category: "Эко-отель",
    description: "Аутентичная усадьба старообрядцев в Уймонской долине с видом на Белуху. Деревянные рубленые дома, домашняя кухня, мёд и травы с собственного хозяйства.",
    price: "от 3 500 ₽/ночь",
    rating: 4.7,
    tags: ["Эко", "Традиции", "Домашняя кухня"],
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.1900,
    lng: 85.9800,
    type: "hotel" as PlaceType,
  },
  // Рестораны
  {
    id: 201,
    name: "Ресторан «Шаман»",
    category: "Алтайская кухня",
    description: "Главный ресторан алтайской кухни в Горно-Алтайске. Маралятина, дичь, рыба из горных рек, кумыс и травяные чаи. Интерьер в духе алтайских традиций.",
    price: "ср. чек 1 200 ₽",
    rating: 4.7,
    tags: ["Национальная кухня", "Дичь", "Рыба"],
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.9580,
    lng: 85.9640,
    type: "restaurant" as PlaceType,
  },
  {
    id: 202,
    name: "Кафе «Кочевник»",
    category: "Национальная кухня",
    description: "Уютное кафе с юртой во дворе. Тепши, курут, боорсок, чегень — настоящая алтайская домашняя еда. Популярное место среди местных жителей.",
    price: "ср. чек 600 ₽",
    rating: 4.5,
    tags: ["Национальная кухня", "Юрта", "Домашняя еда"],
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.9610,
    lng: 85.9700,
    type: "restaurant" as PlaceType,
  },
  {
    id: 203,
    name: "Ресторан «Белуха»",
    category: "Европейская кухня",
    description: "Ресторан с лучшей панорамой на горы в Горно-Алтайске. Европейское меню с местными продуктами, широкая карта алтайских настоек и медовух.",
    price: "ср. чек 1 800 ₽",
    rating: 4.6,
    tags: ["Панорама", "Европейская кухня", "Медовуха"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.9550,
    lng: 85.9600,
    type: "restaurant" as PlaceType,
  },
  {
    id: 204,
    name: "Кафе «Корбу»",
    category: "Рыбный ресторан",
    description: "Рыбное кафе на берегу Телецкого озера. Свежепойманный хариус, линок и телецкий сиг — прямо из озера на стол. Открытая терраса с видом на воду.",
    price: "ср. чек 900 ₽",
    rating: 4.5,
    tags: ["Рыба", "Терраса", "Озеро"],
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.8000,
    lng: 87.2900,
    type: "restaurant" as PlaceType,
  },
  {
    id: 205,
    name: "Семейное кафе «Катунь»",
    category: "Домашняя кухня",
    description: "Небольшое семейное кафе прямо у реки в Чемале. Домашние пироги, борщ и шашлык на живом огне. Летняя веранда нависает над зелёными водами Катуни.",
    price: "ср. чек 700 ₽",
    rating: 4.4,
    tags: ["Домашняя еда", "Шашлык", "Веранда"],
    image: "https://images.unsplash.com/photo-1544148103-0773bf10d330?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.4010,
    lng: 86.0050,
    type: "restaurant" as PlaceType,
  },
  // Музеи
  {
    id: 301,
    name: "Национальный музей им. Анохина",
    category: "Исторический музей",
    description: "Главный музей Республики Алтай. Здесь хранится «Алтайская принцесса» — мумия возрастом 2500 лет, найденная на плато Укок. Богатейшая коллекция скифского золота.",
    price: "вход 350 ₽",
    rating: 4.8,
    tags: ["Мумия", "Скифы", "История"],
    image: "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.9583,
    lng: 85.9600,
    type: "museum" as PlaceType,
  },
  {
    id: 302,
    name: "Музей камня",
    category: "Природный музей",
    description: "Уникальная коллекция минералов, самоцветов и горных пород Алтая. Здесь можно увидеть редкие образцы яшмы, чароита и порфира, а также купить сувениры.",
    price: "вход 200 ₽",
    rating: 4.4,
    tags: ["Минералы", "Геология", "Сувениры"],
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.9570,
    lng: 85.9650,
    type: "museum" as PlaceType,
  },
  {
    id: 303,
    name: "Чемальский краеведческий музей",
    category: "Краеведческий музей",
    description: "Небольшой, но очень насыщенный музей истории Чемальского района. Экспозиции о быте алтайцев, шаманизме, природе и истории освоения края.",
    price: "вход 150 ₽",
    rating: 4.3,
    tags: ["Краеведение", "Быт", "Шаманизм"],
    image: "https://images.unsplash.com/photo-1583470790909-0abb84f63c0c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 51.4028,
    lng: 86.0028,
    type: "museum" as PlaceType,
  },
  {
    id: 304,
    name: "Дом-музей Н.К. Рериха",
    category: "Мемориальный музей",
    description: "Мемориальный дом в селе Верхний Уймон, где останавливался художник Николай Рерих во время Центрально-Азиатской экспедиции 1926 года. Подлинные экспонаты и живопись.",
    price: "вход 250 ₽",
    rating: 4.6,
    tags: ["Живопись", "Экспедиция", "История"],
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.1750,
    lng: 85.9500,
    type: "museum" as PlaceType,
  },
  {
    id: 305,
    name: "Музей петроглифов Калбак-Таш",
    category: "Музей под открытым небом",
    description: "Открытый музей прямо на скалах вдоль Чуйского тракта. Экскурсоводы рассказывают о 5000 наскальных рисунков от бронзового века до тюркского периода.",
    price: "вход 300 ₽",
    rating: 4.6,
    tags: ["Петроглифы", "Под открытым небом", "Экскурсия"],
    image: "https://images.unsplash.com/photo-1615414759007-b14d2cd15e53?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    lat: 50.4200,
    lng: 86.5050,
    type: "museum" as PlaceType,
  },
];

const routes = [
  {
    id: 1,
    title: "«Где Алтай дышит тише»",
    subtitle: "Маршрут для тех, кто устал от шума, людей и вечной гонки. Медленный Алтай, без спешки и героизма.",
    path: "Горно-Алтайск — Чуйский тракт — Семинский перевал",
    description: "Это маршрут не про «успеть всё». Он про ехать, смотреть в окно, выходить из машины просто потому что красиво, и внезапно ловить себя на мысли: «о, я давно так спокойно не дышал». Одно из самых живописных с обзорными точками и горами.",
    tags: ["Горы", "Природа", "История"],
    image: "https://images.unsplash.com/photo-1655047682631-5c4d3330d9b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
  },
  {
    id: 2,
    title: "«Голубые озёра Алтая»",
    subtitle: "Маршрут по самым живописным озёрам горного Алтая. Для тех, кто любит воду и горный воздух.",
    path: "Горно-Алтайск — Телецкое озеро — Мультинские озера",
    description: "Этот маршрут создан для любителей воды и тишины. Телецкое озеро с его кристально чистой водой, Мультинские озёра с бирюзовым отражением гор — каждая остановка это маленькое открытие.",
    tags: ["Озера", "Природа", "Активности"],
    image: "https://images.unsplash.com/photo-1758920206594-b20e4ab58a8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
  },
  {
    id: 3,
    title: "«По следам древних»",
    subtitle: "Историко-культурный маршрут по петроглифам, курганам и сакральным местам Алтая.",
    path: "Горно-Алтайск — Долина Чулышман — Патмосский монастырь",
    description: "Алтай — это не только горы и озёра, но и тысячелетняя история. Маршрут знакомит с петроглифами, древними курганами и священными местами, которые хранят память о народах, живших здесь тысячи лет назад.",
    tags: ["История", "Культура", "Экскурсии"],
    image: "https://images.unsplash.com/photo-1650535877096-928df2bb6365?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
  },
  {
    id: 4,
    title: "«Вершины и перевалы»",
    subtitle: "Активный маршрут для тех, кто хочет испытать себя на высоте. Перевалы, ледники, панорамы.",
    path: "Горно-Алтайск — Ледники Актру — Перевал Кату-Ярык",
    description: "Для настоящих искателей приключений. Ледники Актру, экстремальный серпантин Кату-Ярык и потрясающие панорамные виды — этот маршрут запомнится надолго.",
    tags: ["Горы", "Активности", "Экстрим"],
    image: "https://images.unsplash.com/photo-1566519804250-b33d0f66d88b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
  },
];

const reviews = [
  {
    author: "Анна К.",
    date: "12.02.2024",
    rating: 5,
    text: "Невероятные виды! Поход к горе занял 3 дня, но каждый момент был незабываемым. Рекомендую всем любителям активного отдыха.",
  },
  {
    author: "Михаил В.",
    date: "05.08.2023",
    rating: 5,
    text: "Белуха — это сердце Алтая в прямом смысле слова. Священное место с особой энергетикой. Обязательно вернусь.",
  },
  {
    author: "Елена С.",
    date: "20.07.2023",
    rating: 4,
    text: "Маршрут сложный, но оно того стоит. Вид с ледника на закате — это то, что невозможно передать словами.",
  },
];

async function main() {
  console.log("Seeding database...");

  await prisma.place.createMany({ data: places, skipDuplicates: true });
  console.log(`  ✓ ${places.length} places`);

  await prisma.route.createMany({ data: routes, skipDuplicates: true });
  console.log(`  ✓ ${routes.length} routes`);

  await prisma.review.createMany({ data: reviews, skipDuplicates: true });
  console.log(`  ✓ ${reviews.length} reviews`);

  const defaultSettings = [
    { key: "ai_base_url", value: process.env.ANTHROPIC_API_BASE_URL ?? "https://api.novimundi.space/v1" },
    { key: "ai_model",    value: process.env.ANTHROPIC_MODEL ?? "claude-haiku-4-5" },
    { key: "ai_api_key",  value: process.env.ANTHROPIC_API_KEY ?? "" },
  ];
  for (const s of defaultSettings) {
    await prisma.settings.upsert({ where: { key: s.key }, update: {}, create: s });
  }
  console.log("  ✓ ai settings");

  console.log("Done.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
